// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8rUf19RkBZC-HDTMw6B0pBozQgG6JWpM',
    appId: '1:881682012837:web:6492ad702b270446d50b4c',
    messagingSenderId: '881682012837',
    projectId: 'flutter-backend-api',
    authDomain: 'flutter-backend-api.firebaseapp.com',
    storageBucket: 'flutter-backend-api.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcyNCFsoMnEg5c1ZfeoOCC5EU8XizWweQ',
    appId: '1:881682012837:android:eabb8dfe01a7c8f1d50b4c',
    messagingSenderId: '881682012837',
    projectId: 'flutter-backend-api',
    storageBucket: 'flutter-backend-api.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8E4MnKgDI-9XM5vySIEgvcwrR7fXHfOA',
    appId: '1:881682012837:ios:5fbbdce13f0571dfd50b4c',
    messagingSenderId: '881682012837',
    projectId: 'flutter-backend-api',
    storageBucket: 'flutter-backend-api.appspot.com',
    iosClientId: '881682012837-3sus551ogfh3lft8ar8ajd052lfn0bit.apps.googleusercontent.com',
    iosBundleId: 'com.example.structuredFlutterBackend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8E4MnKgDI-9XM5vySIEgvcwrR7fXHfOA',
    appId: '1:881682012837:ios:5fbbdce13f0571dfd50b4c',
    messagingSenderId: '881682012837',
    projectId: 'flutter-backend-api',
    storageBucket: 'flutter-backend-api.appspot.com',
    iosClientId: '881682012837-3sus551ogfh3lft8ar8ajd052lfn0bit.apps.googleusercontent.com',
    iosBundleId: 'com.example.structuredFlutterBackend',
  );
}
